// 20240905155643
// https://mobilidadeservicos.mogidascruzes.sp.gov.br/api/radar_info

export const localizacao_radares = [
    {
      "id": 65,
      "logradouro": "Av. Dr. Álvaro de Campos Carneiro",
      "numero": "1155",
      "subtipo": "FIXO - Controlador",
      "latitude": "-23.555434",
      "longitude": "-46.196599",
      "sentido": "Bairro-Centro",
      "faixas": 2,
      "kmh": "60",
      "status": "Em operação",
      "justificativa": "Esta via faz parte do corredor do litoral e o equipamento está instalado em um trecho de 700 metros de declive, com transversais de acesso aos bairros, além do constante trânsito de pedestres e escolares, devido aos condomínios populares e à escola infantil na região.\r\n"
    },
    {
      "id": 83,
      "logradouro": "Rua Dr. Ricardo Vilela X Rua Dom Antônio Candido Alvarenga",
      "numero": null,
      "subtipo": "Avanço de Sinal e Parada Sobre Faixa ",
      "latitude": "-23.520420",
      "longitude": "-46.185940",
      "sentido": "Bairro-Centro",
      "faixas": 2,
      "kmh": null,
      "status": "Em operação",
      "justificativa": "Este cruzamento possui grande fluxo, limitações físicas e de visibilidade. Além disso, o trecho anterior na Ricardo Vilela é um longo declive, o que faz com que o equipamento não apenas iniba infrações, mas também induza os condutores a reduzirem imediatamente a velocidade.\r\n"
    },
    {
      "id": 131,
      "logradouro": "Av. Julio Simões oposto",
      "numero": "225",
      "subtipo": "FIXO - Controlador",
      "latitude": "-23.552315",
      "longitude": "-46.213409",
      "sentido": "Centro-Bairro",
      "faixas": 2,
      "kmh": "50",
      "status": "Em operação",
      "justificativa": "Esta área densamente urbanizada, com trânsito intenso de pedestres, veículos lentos e outras interferências, como transversais e uma feira livre aos fins de semana, justifica a instalação do equipamento para aumentar a segurança, especialmente devido à passagem sinalizada de pedestres e à presença de uma escola.\r\n"
    },
    {
      "id": 76,
      "logradouro": "Av. Francisco Ferreira Lopes",
      "numero": "101",
      "subtipo": "FIXO - Redutor ",
      "latitude": "-23.533149",
      "longitude": "-46.209744",
      "sentido": "Bairro-Centro",
      "faixas": 2,
      "kmh": "50",
      "status": "Em operação",
      "justificativa": "Em um longo trecho em linha reta, o equipamento é necessário devido à curva acentuada posterior, conhecida por acidentes frequentes. Além disso, há unidades educacionais instaladas na área. \r\n"
    },
    {
      "id": 63,
      "logradouro": "Av. Prefeito Carlos Alberto Lopes",
      "numero": "635",
      "subtipo": "FIXO - Controlador ",
      "latitude": "-23.542077",
      "longitude": "-46.183097",
      "sentido": "Bairro-Centro e Centro-Bairro",
      "faixas": 3,
      "kmh": "40",
      "status": "Em operação",
      "justificativa": "Esta via apresenta características de risco, como faixa única com dupla ascendente e um declive acentuado, o que propicia o aumento da velocidade dos veículos. Há também um grande número de transversais à esquerda, incluindo vias que servem ao transporte coletivo, com manobras de conversão frequentes, além de ser uma área escolar.\r\n"
    },
    {
      "id": 75,
      "logradouro": "Rodovia Pedro Eroles",
      "numero": "1060",
      "subtipo": "FIXO - Redutor ",
      "latitude": "-23.506079",
      "longitude": "-46.214201",
      "sentido": "Bairro-Centro e Centro-Bairro",
      "faixas": 4,
      "kmh": "60",
      "status": "Em operação",
      "justificativa": "Este trecho permite grande desenvolvimento de velocidade devido às configurações da via, com um leve declive e trecho sinuoso. Há também trânsito de escolares na região, o que demanda a instalação do equipamento. \r\n"
    },
    {
      "id": 88,
      "logradouro": "Av. Valentina Mello Freire Borenstein",
      "numero": "Parque Leon Feffer",
      "subtipo": "FIXO - Controlador",
      "latitude": "-23.528575",
      "longitude": "-46.221675",
      "sentido": "Centro-Bairro",
      "faixas": 2,
      "kmh": "60",
      "status": "Em operação",
      "justificativa": "Este local abriga dispositivos de saúde mental, com travessia frequente de pacientes. Além disso, a existência de um parque público na área requer a redução de velocidade, sendo comum as manobras de veículos pesados, já que a área é industrial. \r\n"
    },
    {
      "id": 68,
      "logradouro": "Av. Shozo Sakai",
      "numero": "1081",
      "subtipo": "FIXO - Controlador",
      "latitude": "-23.551289",
      "longitude": "-46.226991",
      "sentido": "Bairro-Centro e Centro-Bairro",
      "faixas": 2,
      "kmh": "40",
      "status": "Em operação",
      "justificativa": "A área é caracterizada por diversas travessas e declives e aclives sucessivos. Há também uma escola na região, com travessia de escolares na via.\r\n"
    },
    {
      "id": 86,
      "logradouro": "Av. João XXIII x Av. Júlio Perotti",
      "numero": null,
      "subtipo": "AVANÇO DE SINAL",
      "latitude": "-23.515637",
      "longitude": "-46.169386",
      "sentido": "Bairro-Centro e Centro-Bairro",
      "faixas": 4,
      "kmh": null,
      "status": "Inativo",
      "justificativa": "A implementação do avanço de semáforo é sustentada por uma análise técnica detalhada, fundamentada em dados quantitativos e qualitativos. O histórico de acidentes forneceu insights sobre a prevalência de infrações relacionadas à evasão do semáforo vermelho, justificando a necessidade de uma intervenção específica.\r\nA análise de comportamento do tráfego, com foco na dinâmica de movimentação e interação dos veículos no cruzamento em questão, destacou a importância de medidas direcionadas para conter esse padrão de violações. A presença de usuários vulneráveis, especialmente crianças e idosos, é considerada em termos de análise de risco, com o avanço de semáforo sendo uma resposta técnica para mitigar esses riscos.\r\nA implementação desta tecnologia visa não apenas corrigir comportamentos inadequados, mas também otimizar a eficiência do controle semafórico, contribuindo para um ambiente viário mais seguro e fluido, em conformidade com os princípios de gestão avançada de tráfego urbano.\r\n"
    },
    {
      "id": 70,
      "logradouro": "Av. Pref. Francisco Ribeiro Nogueira",
      "numero": "oposto 5001",
      "subtipo": "FIXO - Controlador",
      "latitude": "-23.563713",
      "longitude": "-46.187818",
      "sentido": "Centro-Bairro",
      "faixas": 1,
      "kmh": "50",
      "status": "Em operação",
      "justificativa": "O equipamento está instalado na rampa final da avenida Dr. Álvaro de Campos Carneiro e tem como objetivo reduzir a velocidade dos veículos que seguem na pista em direção a Bertioga, facilitando a fluidez no cruzamento subsequente.\r\n"
    },
    {
      "id": 128,
      "logradouro": "Av. Valentina Mello Freire Borenstein, -300m da Ponte sobre rio Tietê",
      "numero": "",
      "subtipo": "FIXO - Controlador",
      "latitude": "-23.522817",
      "longitude": "-46.224870",
      "sentido": "Bairro-Centro",
      "faixas": 2,
      "kmh": "60",
      "status": "Em operação",
      "justificativa": "Este trecho permite grande desenvolvimento de velocidade devido às configurações da via, com um longo declive seguido por 300 metros de linha reta. A instalação do equipamento impede o aumento excessivo de velocidade. \r\n"
    },
    {
      "id": 91,
      "logradouro": "Av. Julio Simões",
      "numero": "2751",
      "subtipo": "FIXO - Controlador",
      "latitude": "-23.556983",
      "longitude": "-46.207671",
      "sentido": "Bairro-Centro",
      "faixas": 2,
      "kmh": "50",
      "status": "Em operação",
      "justificativa": "Trata-se de uma área densamente urbanizada, com intenso trânsito de pedestres, veículos lentos e outras interferências, como várias transversais. A instalação do equipamento aumenta a segurança, especialmente devido à passagem sinalizada de pedestres e à presença de uma escola. \r\n"
    },
    {
      "id": 89,
      "logradouro": "Av. Kaoru Hiramatsu",
      "numero": "2390",
      "subtipo": "REDUTOR DE VELOCIDADE",
      "latitude": "-23.573950",
      "longitude": "-46.216021",
      "sentido": "Centro-Bairro",
      "faixas": 2,
      "kmh": "40",
      "status": "Inativo",
      "justificativa": "A decisão de implantar um redutor de velocidade eletrônica é resultado de uma análise técnica que contempla diversos fatores relevantes para a segurança viária no local em questão. O histórico de acidentes forneceu uma base empírica para a identificação da necessidade crítica de redução de velocidade. Análises específicas da velocidade média do tráfego indicaram persistentes transgressões aos limites estabelecidos, justificando a implementação desta tecnologia de controle.\r\nA consideração da presença de pedestres, notadamente crianças, idosos e ciclistas, foi conduzida mediante uma análise de padrões de movimentação, levando em conta o volume e a dinâmica do fluxo. A lombada eletrônica é encarada como uma solução técnica para a adaptação do comportamento dos condutores ao ambiente, promovendo uma redução efetiva de velocidade em áreas críticas.\r\nA implantação deste dispositivo não só visa atender às demandas de segurança, mas também alinha-se a estratégias técnicas modernas de gestão de tráfego, contribuindo para uma mobilidade urbana mais segura e integrada.\r\n"
    },
    {
      "id": 80,
      "logradouro": "AV. LOTHAR WALDEMAR HOEHNE",
      "numero": "1747",
      "subtipo": "REDUTOR DE VELOCIDADE",
      "latitude": "-23.504187",
      "longitude": "-46.195268",
      "sentido": "Bairro-Centro",
      "faixas": 2,
      "kmh": "60",
      "status": "Inativo",
      "justificativa": "A decisão de implantar um redutor de velocidade eletrônica é resultado de uma análise técnica que contempla diversos fatores relevantes para a segurança viária no local em questão. O histórico de acidentes forneceu uma base empírica para a identificação da necessidade crítica de redução de velocidade. Análises específicas da velocidade média do tráfego indicaram persistentes transgressões aos limites estabelecidos, justificando a implementação desta tecnologia de controle.\r\nA consideração da presença de pedestres, notadamente crianças, idosos e ciclistas, foi conduzida mediante uma análise de padrões de movimentação, levando em conta o volume e a dinâmica do fluxo. A lombada eletrônica é encarada como uma solução técnica para a adaptação do comportamento dos condutores ao ambiente, promovendo uma redução efetiva de velocidade em áreas críticas.\r\nA implantação deste dispositivo não só visa atender às demandas de segurança, mas também alinha-se a estratégias técnicas modernas de gestão de tráfego, contribuindo para uma mobilidade urbana mais segura e integrada.\r\n"
    },
    {
      "id": 74,
      "logradouro": "Av. Lourenço de Souza Franco",
      "numero": "1231",
      "subtipo": "FIXO - Controlador",
      "latitude": "-23.544680",
      "longitude": "-46.253476",
      "sentido": "Bairro-Centro e Centro-Bairro",
      "faixas": 4,
      "kmh": "60",
      "status": "Em operação",
      "justificativa": "Semelhante ao Fixo 10, este trecho também apresenta grande desenvolvimento de velocidade pelos condutores devido às condições da via. As transversais e travessias de pedestres, além da presença de órgãos municipais, exigem a presença do equipamento. .\r\n"
    },
    {
      "id": 126,
      "logradouro": "AVENIDA JAPÃO",
      "numero": "961",
      "subtipo": "FIXO - Redutor ",
      "latitude": "-23.537181",
      "longitude": "-46.203577",
      "sentido": "Bairro-Centro e Centro-Bairro",
      "faixas": 2,
      "kmh": "40",
      "status": "Em operação",
      "justificativa": "Trecho com acentuado declive e aclive, grande quantidade de transversais e áreas comerciais com recuos.\r\n"
    },
    {
      "id": 85,
      "logradouro": "Estrada do Evangelho Pleno x Rodovia Pedro Eroles",
      "numero": "1887",
      "subtipo": "FIXO - Redutor ",
      "latitude": "-23.505716",
      "longitude": "-46.217628",
      "sentido": "Bairro-Centro",
      "faixas": 1,
      "kmh": "40",
      "status": "Em operação",
      "justificativa": "Parte do corredor do litoral e da rota obrigatória de veículos pesados, o equipamento foi instalado em um trecho de 800 metros de declive, onde a estrada do Evangelho Pleno é caracterizada por sinuosidade, exigindo a presença do redutor. \r\n"
    },
    {
      "id": 90,
      "logradouro": "Av. Francisco Rodrigues Filho (Parque Centenário)",
      "numero": null,
      "subtipo": "AVANÇO DE SINAL",
      "latitude": "-23.508056",
      "longitude": "-46.172711",
      "sentido": "Bairro-Centro e Centro-Bairro",
      "faixas": 4,
      "kmh": null,
      "status": "Em operação",
      "justificativa": "A implementação do avanço de semáforo é sustentada por uma análise técnica detalhada, fundamentada em dados quantitativos e qualitativos. O histórico de acidentes forneceu insights sobre a prevalência de infrações relacionadas à evasão do semáforo vermelho, justificando a necessidade de uma intervenção específica.\r\nA análise de comportamento do tráfego, com foco na dinâmica de movimentação e interação dos veículos no cruzamento em questão, destacou a importância de medidas direcionadas para conter esse padrão de violações. A presença de usuários vulneráveis, especialmente crianças e idosos, é considerada em termos de análise de risco, com o avanço de semáforo sendo uma resposta técnica para mitigar esses riscos.\r\nA implementação desta tecnologia visa não apenas corrigir comportamentos inadequados, mas também otimizar a eficiência do controle semafórico, contribuindo para um ambiente viário mais seguro e fluido, em conformidade com os princípios de gestão avançada de tráfego urbano.\r\n"
    },
    {
      "id": 66,
      "logradouro": "Av. Francisco Ferreira Lopes",
      "numero": "4410 + 40m",
      "subtipo": "FIXO - Controlador",
      "latitude": "-23.542278",
      "longitude": "-46.241881",
      "sentido": "Centro-Bairro",
      "faixas": 2,
      "kmh": "60",
      "status": "Em operação",
      "justificativa": "O trecho em questão possui 300 metros de declive e curva, com trânsito constante de veículos pesados. Após o equipamento, há uma ponte e um cruzamento semaforizado.\r\n"
    },
    {
      "id": 82,
      "logradouro": "Av. Henrique Peres X Av. Dom Luiz de Souza",
      "numero": null,
      "subtipo": "Avanço de Sinal e Parada Sobre Faixa ",
      "latitude": "-23.546117",
      "longitude": "-46.206026",
      "sentido": "Bairro-Centro e Centro-Bairro",
      "faixas": 2,
      "kmh": null,
      "status": "Em operação",
      "justificativa": "Devido ao grande fluxo de veículos, especialmente por se tratar de um corredor com destino ao litoral, e considerando as dimensões do cruzamento e a grande quantidade de movimentos viários, além do tráfego constante de pedestres, a operação do equipamento nesse local é necessária para inibir infrações. \r\n"
    },
    {
      "id": 73,
      "logradouro": "Av. Antonio de Almeida oposto",
      "numero": "1035",
      "subtipo": "REDUTOR DE VELOCIDADE",
      "latitude": "-23.503111",
      "longitude": "-46.181309",
      "sentido": "Centro-Bairro",
      "faixas": 1,
      "kmh": "40",
      "status": "Inativo",
      "justificativa": "A decisão de implantar um redutor de velocidade eletrônica é resultado de uma análise técnica que contempla diversos fatores relevantes para a segurança viária no local em questão. O histórico de acidentes forneceu uma base empírica para a identificação da necessidade crítica de redução de velocidade. Análises específicas da velocidade média do tráfego indicaram persistentes transgressões aos limites estabelecidos, justificando a implementação desta tecnologia de controle.\r\nA consideração da presença de pedestres, notadamente crianças, idosos e ciclistas, foi conduzida mediante uma análise de padrões de movimentação, levando em conta o volume e a dinâmica do fluxo. A lombada eletrônica é encarada como uma solução técnica para a adaptação do comportamento dos condutores ao ambiente, promovendo uma redução efetiva de velocidade em áreas críticas.\r\nA implantação deste dispositivo não só visa atender às demandas de segurança, mas também alinha-se a estratégias técnicas modernas de gestão de tráfego, contribuindo para uma mobilidade urbana mais segura e integrada.\r\n"
    },
    {
      "id": 130,
      "logradouro": "Av. Pref. Francisco Ribeiro Nogueira x Av. Pedro Machado",
      "numero": null,
      "subtipo": "Avanço de Sinal e Parada Sobre Faixa ",
      "latitude": "-23.538299",
      "longitude": "-46.192361",
      "sentido": "Bairro-Centro",
      "faixas": 2,
      "kmh": null,
      "status": "Em operação",
      "justificativa": "Trata-se de um cruzamento com fluxo constante, e as dimensões do cruzamento, as fases semafóricas e os movimentos permitidos tornam essencial a operação do equipamento para inibir infrações. O cruzamento também conta com travessia de pedestres sinalizada e botoeira.\r\n"
    },
    {
      "id": 132,
      "logradouro": "Av. Gov. Adhemar de Barros menos 40m do nº",
      "numero": "127",
      "subtipo": "FIXO - Redutor ",
      "latitude": "-23.525938",
      "longitude": "-46.205782",
      "sentido": "Centro-Bairro",
      "faixas": 1,
      "kmh": "50",
      "status": "Em operação",
      "justificativa": "A via apresenta perfil limitado em termos de faixas de rodagem, além de várias transversais e manobras frequentes de conversão. A existência de uma ciclovia justifica a instalação do equipamento. \r\n"
    },
    {
      "id": 129,
      "logradouro": "Av. Francisco Rodrigues Filho x Av. José Moreira Filho",
      "numero": null,
      "subtipo": "AVANÇO DE SINAL",
      "latitude": "-23.518155",
      "longitude": "-46.193051",
      "sentido": "Centro-Bairro",
      "faixas": 2,
      "kmh": null,
      "status": "Inativo",
      "justificativa": "A implementação do avanço de semáforo é sustentada por uma análise técnica detalhada, fundamentada em dados quantitativos e qualitativos. O histórico de acidentes forneceu insights sobre a prevalência de infrações relacionadas à evasão do semáforo vermelho, justificando a necessidade de uma intervenção específica.A análise de comportamento do tráfego, com foco na dinâmica de movimentação e interação dos veículos no cruzamento em questão, destacou a importância de medidas direcionadas para conter esse padrão de violações. A presença de usuários vulneráveis, especialmente crianças e idosos, é considerada em termos de análise de risco, com o avanço de semáforo sendo uma resposta técnica para mitigar esses riscos.A implementação desta tecnologia visa não apenas corrigir comportamentos inadequados, mas também otimizar a eficiência do controle semafórico, contribuindo para um ambiente viário mais seguro e fluido, em conformidade com os princípios de gestão avançada de tráfego urbano."
    },
    {
      "id": 69,
      "logradouro": "Rua Dr. Deodato Wertheimer",
      "numero": "2351 e 2362",
      "subtipo": "FIXO - Controlador",
      "latitude": "-23.531213",
      "longitude": "-46.193645",
      "sentido": "Bairro-Centro e Centro-Bairro",
      "faixas": 3,
      "kmh": "40",
      "status": "Em operação",
      "justificativa": "Este trecho da via está situado em uma área de manobras, com transversais em ambos os lados. O trânsito de pessoas com necessidades especiais é comum devido à presença de instituições dedicadas a esse público. .\r\n"
    },
    {
      "id": 71,
      "logradouro": "Av. Japão",
      "numero": "7200",
      "subtipo": "FIXO - Controlador",
      "latitude": "-23.576800",
      "longitude": "-46.221594",
      "sentido": "Bairro-Centro e Centro-Bairro",
      "faixas": 2,
      "kmh": "40",
      "status": "Em operação",
      "justificativa": "Este local apresenta intenso trânsito de pedestres e diversas transversais. O trecho onde o equipamento está instalado é em declive, e o controlador de velocidade atua para coibir o aumento excessivo da velocidade.\r\n"
    },
    {
      "id": 79,
      "logradouro": "Rua Cabo Diogo Oliver",
      "numero": "1077",
      "subtipo": "FIXO - Redutor ",
      "latitude": "-23.514668",
      "longitude": "-46.203451",
      "sentido": "Bairro-Centro e Centro-Bairro",
      "faixas": 2,
      "kmh": "40",
      "status": "Em operação",
      "justificativa": "Este local possui limitações físicas, pista estreita e uma ponte sobre o Rio Tietê, com limitações semelhantes nas faixas de rolamento. A travessia de animais silvestres é comum por ser uma região de várzea. \r\n"
    },
    {
      "id": 92,
      "logradouro": "Av. Julio Simões",
      "numero": "oposto 2905",
      "subtipo": "FIXO - Controlador",
      "latitude": "-23.557907",
      "longitude": "-46.206640",
      "sentido": "Centro-Bairro",
      "faixas": 2,
      "kmh": "50",
      "status": "Inativo",
      "justificativa": "Semelhante ao Fixo 29, esta área densamente urbanizada apresenta trânsito intenso de pedestres e várias interferências. A instalação do equipamento melhora a segurança, especialmente devido à presença de uma escola e à passagem de pedestres. \r\n"
    },
    {
      "id": 64,
      "logradouro": "Av. Henrique Peres",
      "numero": "190",
      "subtipo": "FIXO - Controlador ",
      "latitude": "-23.537036",
      "longitude": "-46.219185",
      "sentido": "Centro-Bairro",
      "faixas": 2,
      "kmh": "40",
      "status": "Em operação",
      "justificativa": "O equipamento foi instalado devido ao grande fluxo de veículos, sendo um corredor com destino ao litoral. A porção anterior do equipamento está localizada na rampa do viaduto Argeu Batalha, onde os veículos tendem a desenvolver grande velocidade. Além disso, há uma travessia de pedestres e uma escola infantil na área.\r\n"
    },
    {
      "id": 78,
      "logradouro": "Av. Dr. Álvaro de Campos Carneiro",
      "numero": "215",
      "subtipo": "REDUTOR DE VELOCIDADE",
      "latitude": "-23.549593173229844",
      "longitude": "-46.202731007568396",
      "sentido": "Bairro-Centro e Centro-Bairro",
      "faixas": 4,
      "kmh": "40",
      "status": "Inativo",
      "justificativa": "A decisão de implantar um redutor de velocidade eletrônica é resultado de uma análise técnica que contempla diversos fatores relevantes para a segurança viária no local em questão. O histórico de acidentes forneceu uma base empírica para a identificação da necessidade crítica de redução de velocidade. Análises específicas da velocidade média do tráfego indicaram persistentes transgressões aos limites estabelecidos, justificando a implementação desta tecnologia de controle.\r\nA consideração da presença de pedestres, notadamente crianças, idosos e ciclistas, foi conduzida mediante uma análise de padrões de movimentação, levando em conta o volume e a dinâmica do fluxo. A lombada eletrônica é encarada como uma solução técnica para a adaptação do comportamento dos condutores ao ambiente, promovendo uma redução efetiva de velocidade em áreas críticas.\r\nA implantação deste dispositivo não só visa atender às demandas de segurança, mas também alinha-se a estratégias técnicas modernas de gestão de tráfego, contribuindo para uma mobilidade urbana mais segura e integrada.\r\n"
    },
    {
      "id": 67,
      "logradouro": "Av. Dr. Álvaro de Campos Carneiro",
      "numero": "450",
      "subtipo": "FIXO - Controlador",
      "latitude": "-23.551520",
      "longitude": "-46.201685",
      "sentido": "Centro-Bairro",
      "faixas": 2,
      "kmh": "60",
      "status": "Em operação",
      "justificativa": "O local possui uma área de retorno e a saída do bairro Vila Brasileira pela rua Martimiano Rodrigues da Silva. O constante trânsito de pedestres e as manobras de conversão frequentes, além de ser um ponto de retorno do transporte coletivo, justificam a instalação do equipamento.\r\n"
    },
    {
      "id": 125,
      "logradouro": "AVENIDA GUILHERME GEORGE",
      "numero": "2336",
      "subtipo": "FIXO - Redutor ",
      "latitude": "-23.540459",
      "longitude": "-46.270343",
      "sentido": "Bairro-Centro e Centro-Bairro",
      "faixas": 2,
      "kmh": "40",
      "status": "Em operação",
      "justificativa": "O local possui uma ponte sobre o Rio Taiaçupeba e travessia de animais silvestres devido à área de várzea. Como é uma divisa de município, há fiscalização de trânsito e registro de emplacamentos de veículos. \r\n"
    },
    {
      "id": 138,
      "logradouro": "Av. Henrique Peres X Rua Francisco Rodrigues Passos",
      "numero": null,
      "subtipo": "AVANÇO DE SINAL",
      "latitude": "-23.546117",
      "longitude": "-46.206026",
      "sentido": "Bairro-Centro e Centro-Bairro",
      "faixas": 2,
      "kmh": null,
      "status": "Em operação",
      "justificativa": "A implementação do avanço de semáforo é sustentada por uma análise técnica detalhada, fundamentada em dados quantitativos e qualitativos. O histórico de acidentes forneceu insights sobre a prevalência de infrações relacionadas à evasão do semáforo vermelho, justificando a necessidade de uma intervenção específica.\r\nA análise de comportamento do tráfego, com foco na dinâmica de movimentação e interação dos veículos no cruzamento em questão, destacou a importância de medidas direcionadas para conter esse padrão de violações. A presença de usuários vulneráveis, especialmente crianças e idosos, é considerada em termos de análise de risco, com o avanço de semáforo sendo uma resposta técnica para mitigar esses riscos.\r\nA implementação desta tecnologia visa não apenas corrigir comportamentos inadequados, mas também otimizar a eficiência do controle semafórico, contribuindo para um ambiente viário mais seguro e fluido, em conformidade com os princípios de gestão avançada de tráfego urbano.\r\n"
    },
    {
      "id": 84,
      "logradouro": "Av. Dr. Álvaro de Campos Carneiro",
      "numero": "443 + 500m",
      "subtipo": "FIXO - Redutor ",
      "latitude": "-23.560408",
      "longitude": "-46.191597",
      "sentido": "Centro-Bairro",
      "faixas": 2,
      "kmh": "60",
      "status": "Em operação",
      "justificativa": "A via, que integra o corredor do litoral, possui um trecho de 780 metros de declive, o que justifica a instalação do redutor de velocidade. Existem dispositivos de retorno na área, tornando a faixa esquerda usual para acesso a esses dispositivos. \r\n"
    },
    {
      "id": 77,
      "logradouro": "Av. Japão",
      "numero": "3978 + 850m",
      "subtipo": "FIXO - Redutor ",
      "latitude": "-23.568048",
      "longitude": "-46.214820",
      "sentido": "Centro-Bairro",
      "faixas": 2,
      "kmh": "40",
      "status": "Em operação",
      "justificativa": "Local com longo trecho em declive seguido de curva acentuada, transversais e faixas de retorno. \r\n"
    },
    {
      "id": 72,
      "logradouro": "Av. Lourenço de Souza Franco",
      "numero": "2442",
      "subtipo": "FIXO - Controlador",
      "latitude": "-23.541762",
      "longitude": "-46.268609",
      "sentido": "Bairro-Centro e Centro-Bairro",
      "faixas": 4,
      "kmh": "60",
      "status": "Em operação",
      "justificativa": "Trata-se de um trecho onde os condutores tendem a desenvolver grande velocidade devido ao bom pavimento e à ausência de impedimentos. A grande quantidade de transversais, travessias de pedestres e a presença de órgãos municipais, como a base da Guarda Civil Municipal, justificam a instalação do equipamento.\r\n"
    },
    {
      "id": 81,
      "logradouro": "Av. Joaquim Pereira de Carvalho",
      "numero": "518",
      "subtipo": "FIXO - Redutor ",
      "latitude": "-23.514086",
      "longitude": "-46.213920",
      "sentido": "Centro-Bairro e Bairro-Centro",
      "faixas": 4,
      "kmh": "40",
      "status": "Em operação",
      "justificativa": "O trecho apresenta pistas sinuosas, com uma curva acentuada à esquerda, exigindo imediata redução de velocidade.\r\n"
    },
    {
      "id": 87,
      "logradouro": "Av. Ten. Onofre Rodrigues de Aguiar",
      "numero": "901",
      "subtipo": "FIXO - Controlador",
      "latitude": "-23.526382",
      "longitude": "-46.214586",
      "sentido": "Bairro-Centro e Centro-Bairro",
      "faixas": 4,
      "kmh": "50",
      "status": "Em operação",
      "justificativa": "O trecho possui grande desenvolvimento de velocidade pelos condutores devido ao bom pavimento e à ausência de impedimentos. A via é caracterizada por manobras constantes de veículos pesados, dado que a área é predominantemente industrial.\r\n"
    },
    {
      "id": 133,
      "logradouro": "Av. Lothar Waldemar Hoehne oposto",
      "numero": "1846",
      "subtipo": "FIXO - Redutor ",
      "latitude": "-23.502558",
      "longitude": "-46.191933",
      "sentido": "Bairro-Centro",
      "faixas": 2,
      "kmh": "50",
      "status": "Em operação",
      "justificativa": "Esta via possui trechos com longas retas e outros sinuosos. A presença de travessia de escolares e o intenso trânsito de escolares, juntamente com uma curva acentuada precedida de rotatória, justificam o uso do equipamento. \r\n"
    },
    {
      "id": 134,
      "logradouro": "Av. Kaoru Hiramatsu +50m do nº",
      "numero": "100",
      "subtipo": "FIXO - Redutor ",
      "latitude": "-23.571979",
      "longitude": "-46.205593",
      "sentido": "Bairro-Centro",
      "faixas": 2,
      "kmh": "40",
      "status": "Em operação",
      "justificativa": "Local com longo trecho em declive seguido de curva acentuada e transversais, além de faixas de retorno. É comum o trânsito de maquinário agrícola, além de escolares e alunos de uma instituição próxima. \r\n"
    }
    , {
      "id": 135,
      "logradouro": "Rua Dr. Correa x Rua Barão de Jaceguai ",
      "numero": "100",
      "subtipo": "FIXO - Redutor ",
      "latitude": "-23.5214264",
      "longitude": "-46.1899999",
      "sentido": "Centro-Bairro",
      "faixas": "",
      "kmh": "",
      "status": "Em operação",
      "justificativa": "O cruzamento em questão possui grande fluxo, limitações físicas e de visibilidade. A presença de uma travessia sinalizada de pedestres, aliada a essas limitações, bem como as características de fluxo das vias, que são corredores troncais do transporte coletivo, justificam a instalação do equipamento para inibir o avanço semafórico. "
    }
  ]